name: Build Project

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  paths:
    - ".github/**"
    - "FNLogs.Client/**"

env:
  DOTNET_MAJOR_MINOR: "8.0"
  DOTNET_CONFIGURATION: "Release"

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET ${{ env.DOTNET_MAJOR_MINOR }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "${{ env.DOTNET_MAJOR_MINOR }}.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish
        run: dotnet publish FNLogs.Client/FNLogs.Client.csproj --no-restore -c ${{ env.DOTNET_CONFIGURATION }} --output ./publish

      - name: Upload Build Artifact(s)
        uses: actions/upload-artifact@v4
        with:
          name: fn-logs-client
          path: ./publish
